try to fix workflow

diff --git a/.github/workflows/make-release.yml b/.github/workflows/make-release.yml
--- a/.github/workflows/make-release.yml
+++ b/.github/workflows/make-release.yml
@@ -45,46 +45,38 @@ jobs:
           draft: false
           prerelease: false
 
+      - name: Install GitHub CLI
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y gh
+
+      - name: Authenticate GitHub CLI
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
+          gh auth status
+
       - name: Upload Release Assets
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          # Find all files to upload
-          files=$(find releases -name '*.json.xz')
-
-          # Loop over files and upload each one
-          for file in $files; do
+          echo "Release ID: ${{ steps.create_release.outputs.id }}"
+          for file in releases/*.json.xz; do
             echo "Uploading $file"
-            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
-                 -H "Content-Type: application/zip" \
-                 --data-binary @"$file" \
-                 "${{ steps.create_release.outputs.upload_url }}?name=$(basename $file)"
+            gh release upload ${{ steps.create_release.outputs.id }} "$file" --clobber || echo "Failed to upload $file"
           done
 
       - name: Remove old releases
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          # Install GitHub CLI
-          sudo apt-get update
-          sudo apt-get install -y gh
-
-          # Authenticate GitHub CLI
-          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
-
-          # Get the current date in seconds since epoch
           current_date=$(date +%s)
-
-          # List all releases
           gh release list --limit 100 | while read -r release; do
             release_date=$(echo $release | awk '{print $NF}')
             release_date_seconds=$(date -d $release_date +%s)
             release_id=$(echo $release | awk '{print $1}')
-
-            # Calculate the age of the release in days
             release_age_days=$(( (current_date - release_date_seconds) / 86400 ))
-
-            # Delete releases older than 30 days
             if [ $release_age_days -gt 30 ]; then
               echo "Deleting release $release_id (age: $release_age_days days)"
               gh release delete $release_id --yes
